### ISSUE TITLE
Convert all RST files to GFM

### ISSUE THREAD

**Issue by pydanny** [pydanny/cached-property#120]
# Justifications
- Writing in Markdown is easier/faster than RST, facilitating improved documentation
- Markdown has a lower barrier of entry
- Advancements in Twine it's checkable *before* deploying a new release to PyPI. I'm really tired of having `x.x.x` releases simply because the RST doesn't compile.

# Tasks 
- [ ] Use [Pandoc](http://pandoc.org/) for conversion on all files. Example: `pandoc README.rst -t gfm -o README.md`
- [ ] Remove `sourceCode` label from generated markdown files
- [ ] Remove .rst files
- [ ] Change rst file references in `setup.py` and in other places.

**Comment by althonos** [comment]
I'd also suggest changing the `HISTORY.rst` to a `CHANGELOG.md` file following the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format ! I can create a PR for this.

**Comment by pydanny** [comment]
Resolved by #234
